services:
  backend:
    build:
      context: ./backend/
      dockerfile: Dockerfile.dev
    container_name: vault-36-central-computer
    restart: unless-stopped
    volumes:
      - "./backend:/usr/src/app"
      - sqlite_data:/db/data
    ports:
      - 4001:3001

  frontend:
    build:
      context: ./frontend/
      dockerfile: Dockerfile
    container_name: vault-36-terminal
    restart: unless-stopped
    ports:
      - 4000:3000
    depends_on:
      - backend
    volumes:
      - "./frontend:/usr/src/app"
      - "/usr/src/app/node_modules"

  nginx:
    build:
      context: ./proxy/
    restart: unless-stopped
    container_name: vault-36-proxy
    ports:
      - 80:80
    depends_on:
      - frontend
      - backend

volumes:
  sqlite_data:
