FROM alpine:latest
# Install SQLite
RUN apk --no-cache add sqlite
# Create a directory to store the database
WORKDIR /db
# Copy our SQLite database file into the container
COPY initial-db.sqlite /db/
# Expose the port if needed
# Expose 1433
# Command to run when the container starts
CMD ["sqlite3", "/data/initial-db.sqlite"]
